"""
EXP3 multi-armed bandit mirror router for ReliaDL.

Chooses which mirror to issue the next range request to when a file is
available from several CDN edges or replicas. The problem is adversarial rather
than merely noisy: an edge node's throughput depends on other tenants' load,
routing changes and cache state, none of which are stationary and none of which
are observable. EXP3 is the right tool because it assumes nothing about the
reward distribution — no independence, no stationarity, not even that rewards
are generated by a process rather than chosen to spite us.

Only the reward of the mirror actually used is observed; the counterfactual
throughput of the mirrors not chosen is unknowable. That is what makes this a
bandit rather than a prediction problem, and it is the constraint the algorithm
is built around:

    p_{m,t} = (1 - eta) * w_{m,t} / sum_j w_{j,t}  +  eta / M
    r_hat   = r / p_{m,t}
    w_{m,t+1} = w_{m,t} * exp(eta * r_hat / M)

The uniform eta/M floor does two jobs, and the second is easy to overlook.
It keeps every mirror under occasional test so a recovered edge can be
rediscovered, and it bounds every selection probability away from zero, which
is what makes the importance-weighted estimate r/p finite. Dividing by a
probability that could reach zero would be unbounded; the floor is what makes
the estimator well defined rather than merely convenient.

Dividing by the selection probability is what keeps the estimate unbiased. A
mirror chosen a tenth of the time has its observed reward scaled up tenfold, so
in expectation each arm's accumulated estimate reflects what it would have
earned had it been played every round. Without that correction the algorithm
would conflate "rarely chosen" with "low reward" and never escape its first
impression.

Numerical representation
------------------------
Weights are held as logarithms, which is a requirement rather than a
refinement. The exponent of a single update is bounded by 1 — since
r <= 1 and p >= eta/M give r_hat <= M/eta, so eta * r_hat / M <= 1 — but that
bound is per round, and it accumulates. A weight can therefore grow like e^T
over T rounds, and a long download makes tens of thousands of range requests;
e^10000 is not representable. In log space the same growth is linear and the
weights are rescaled after every update so the largest is exactly 1, which
leaves the selection distribution untouched (it depends only on weight ratios)
while keeping every exponential in range.

Tracking a moving target
------------------------
Classic EXP3 has vanishing regret against the best *fixed* arm in hindsight,
which is the wrong target here: over a long transfer the best mirror changes.
Accumulated weights make the algorithm progressively more confident and
correspondingly slower to react, so an edge that was fastest for the first ten
thousand chunks keeps its lead long after it has degraded.

The optional decay mixes each weight back toward the mean every round,

    w_m <- (1 - alpha) * w_m + (alpha / M) * sum_j w_j

which caps how much evidence any arm can hoard and gives the router a finite
memory. This is the EXP3.S variant, and it is what converts a bandit that
converges into one that tracks. With alpha = 0 the behaviour is exactly classic
EXP3.

Choosing the decay is a real tradeoff, so it was measured rather than guessed.
Regret against the best mirror in hindsight, three mirrors, eta = 0.1, averaged
over 24 seeded trials of 5000 rounds, under a stationary schedule, an abrupt
mid-transfer failover, and a gradual drift. The reward stream is seeded
independently of the router's own sampler; sharing a seed makes the two draw
identical values in lockstep and couples each reward to the arm that draw
selected, which quietly favours whichever mirror sits first in the cumulative
distribution:

    decay     stationary   switching   drifting   worst
    0                217        1709        771    1709
    0.0002           246         378        222     378
    0.0005           279         390        235     390
    0.001            333         426        256     426
    0.002            420         494        311     494
    0.004            578         633        397     633

Classic EXP3 wins the stationary column and is unusable everywhere else: having
committed to the leading mirror it cannot recover when that mirror degrades,
which is the single behaviour this router exists to avoid. Any small positive
decay cuts worst-case regret by more than four times for about a tenth more
regret in the stationary case, which is a trade worth making for a transfer
whose mirrors are not under our control.

The optimum sat at alpha = 0.0002, which is 1/T for the 5000-round horizon
measured. That is not a coincidence — it is the EXP3.S guidance alpha ~ 1/T —
and it was confirmed to hold at other horizons, alpha = 1/T minimizing
worst-case regret at T = 1000, 2000 and 10000 alike. ``decay_for_horizon``
applies that relationship for callers who know how many range requests a
transfer will make.
"""

from __future__ import annotations

import math
import random
import threading
import time
from dataclasses import dataclass
from enum import Enum
from typing import Callable, Dict, List, Optional, Sequence, Tuple

from src.exceptions import ConfigurationError
from src.models import ChunkSpec

# Fraction of each round's probability mass spread uniformly across mirrors.
# Also the floor on any selection probability, and therefore the cap on the
# importance weight 1/p.
DEFAULT_EXPLORATION_RATE = 0.1

# Per-round pull of every weight back toward the mean. Zero reproduces classic
# EXP3, which converges on the best fixed mirror; a positive value bounds the
# algorithm's memory so it can follow a mirror that degrades mid-transfer.
#
# The default corresponds to 1 / 2000 — a couple of thousand range requests,
# roughly a 16 GB transfer at the default 8 MB chunk. Callers who know their
# chunk count should pass decay_for_horizon(count) instead; see the module
# docstring for the measurements behind this.
DEFAULT_WEIGHT_DECAY = 0.0005

# Horizon the default decay is tuned for, in rounds.
DEFAULT_HORIZON_ROUNDS = 2000

# Natural log of zero, the weight of an arm that can never be selected. Used as
# the identity for log-space accumulation.
_LOG_ZERO = -math.inf


def _logaddexp(left: float, right: float) -> float:
    """
    Compute log(exp(left) + exp(right)) without leaving log space.

    Factors out the larger term so the surviving exponential has a
    non-positive argument and cannot overflow, and uses log1p for accuracy when
    the two terms are far apart and the correction is tiny.
    """
    if left == _LOG_ZERO:
        return right
    if right == _LOG_ZERO:
        return left
    higher, lower = (left, right) if left > right else (right, left)
    return higher + math.log1p(math.exp(lower - higher))


def _logsumexp(values: Sequence[float]) -> float:
    """Compute log(sum(exp(v))) by shifting out the maximum term first."""
    if not values:
        return _LOG_ZERO
    highest = max(values)
    if highest == _LOG_ZERO:
        return _LOG_ZERO
    total = sum(math.exp(value - highest) for value in values)
    return highest + math.log(total)


def decay_for_horizon(expected_rounds: int) -> float:
    """
    Weight decay for a transfer of a known length, following alpha ~ 1/T.

    The EXP3.S guidance, and measured to minimize worst-case regret at horizons
    from a thousand rounds to ten thousand. A download's horizon is the number
    of range requests it expects to issue, roughly file size over chunk size.

    Raises:
        ConfigurationError: If expected_rounds is not a positive integer.
    """
    if isinstance(expected_rounds, bool) or not isinstance(expected_rounds, int):
        raise ConfigurationError(
            f"expected_rounds must be an integer, got {type(expected_rounds).__name__}",
            parameter="expected_rounds",
            value=expected_rounds,
        )
    if expected_rounds < 1:
        raise ConfigurationError(
            f"expected_rounds must be at least 1, got {expected_rounds}",
            parameter="expected_rounds",
            value=expected_rounds,
        )
    # A one-round transfer has nothing to forget; cap at 1 so the value stays a
    # valid mixing coefficient.
    return min(1.0, 1.0 / expected_rounds)


def _validate_unit_interval(
    value: float, parameter: str, allow_zero: bool = False
) -> float:
    """
    Validate that a rate lies in (0, 1], or [0, 1] when zero is meaningful.

    Raises:
        ConfigurationError: If the value is non-numeric, non-finite, or out of range.
    """
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ConfigurationError(
            f"{parameter} must be numeric, got {type(value).__name__}",
            parameter=parameter,
            value=value,
        )
    numeric = float(value)
    if not math.isfinite(numeric):
        raise ConfigurationError(
            f"{parameter} must be finite, got {value}",
            parameter=parameter,
            value=value,
        )
    lower_ok = numeric >= 0.0 if allow_zero else numeric > 0.0
    if not lower_ok or numeric > 1.0:
        bound = "[0, 1]" if allow_zero else "(0, 1]"
        raise ConfigurationError(
            f"{parameter} must lie in {bound}, got {value}",
            parameter=parameter,
            value=value,
        )
    return numeric


@dataclass(frozen=True)
class ArmSelection:
    """
    One mirror choice, carrying the probability that produced it.

    The probability travels with the selection rather than being recomputed at
    update time, and that is a correctness requirement, not bookkeeping. The
    importance-weighted estimate r/p is only unbiased when p is the probability
    the action was actually drawn from; weights shift on every intervening
    update, so a probability recomputed later belongs to a different
    distribution and would bias every estimate in flight. A download issues
    many concurrent range requests, so rewards routinely arrive well after the
    selection that caused them.

    Attributes:
        arm: Identifier of the chosen mirror.
        probability: Probability this arm was drawn with, in (0, 1].
        round_index: Round number at which the draw was made, from zero.
    """

    arm: str
    probability: float
    round_index: int

    @property
    def importance_weight(self) -> float:
        """
        Reciprocal of the selection probability, the estimator's scale factor.

        Bounded by M / eta because the uniform exploration floor bounds the
        probability away from zero.
        """
        return 1.0 / self.probability

    def __repr__(self) -> str:
        return (
            f"ArmSelection(arm={self.arm!r}, probability={self.probability:.6f}, "
            f"round={self.round_index})"
        )


@dataclass(frozen=True)
class WeightUpdate:
    """
    Record of one weight update, retaining the intermediate terms.

    Exposed for observability and for the tests that pin the algebra: a router
    that silently mis-scales its estimates produces a plausible-looking
    distribution that quietly converges on the wrong mirror, so the terms are
    worth being able to inspect.

    Attributes:
        arm: Mirror whose weight was updated.
        reward: Observed reward in [0, 1].
        probability: Probability the arm was selected with.
        estimated_reward: Importance-weighted estimate reward / probability.
        log_weight_delta: Amount added to the arm's log weight.
        round_index: Round at which the update was applied.
    """

    arm: str
    reward: float
    probability: float
    estimated_reward: float
    log_weight_delta: float
    round_index: int

    def __repr__(self) -> str:
        return (
            f"WeightUpdate(arm={self.arm!r}, reward={self.reward:.4f}, "
            f"r_hat={self.estimated_reward:.4f}, "
            f"delta={self.log_weight_delta:.6f})"
        )


class EXP3Bandit:
    """
    Non-stationary EXP3 mirror router over a fixed set of arms.

    Thread-safe. A download engine dispatches range requests from many workers
    at once, so selection and update are serialized internally; the critical
    section is a handful of arithmetic operations over the arm set and is never
    held across I/O.

    Weights are stored as logarithms and rescaled after every update, so the
    router is safe to run for the lifetime of an arbitrarily long transfer.
    """

    def __init__(
        self,
        arms: Sequence[str],
        exploration_rate: float = DEFAULT_EXPLORATION_RATE,
        weight_decay: float = DEFAULT_WEIGHT_DECAY,
        seed: Optional[int] = None,
    ) -> None:
        validated = self._validate_arms(arms)
        self._arms: Tuple[str, ...] = validated
        self._index = {arm: position for position, arm in enumerate(validated)}
        self._eta = _validate_unit_interval(exploration_rate, "exploration_rate")
        self._decay = _validate_unit_interval(
            weight_decay, "weight_decay", allow_zero=True
        )

        # Uniform prior: every mirror starts equally plausible, since before the
        # first request there is no evidence to prefer any of them.
        self._log_weights: List[float] = [0.0] * len(validated)
        self._rounds = 0
        self._random = random.Random(seed)
        self._lock = threading.RLock()

    @staticmethod
    def _validate_arms(arms: Sequence[str]) -> Tuple[str, ...]:
        """
        Validate the mirror set.

        Duplicates are rejected rather than collapsed: two entries for one
        mirror would split its evidence across two weights and let it draw
        twice the exploration mass, quietly biasing the router toward whichever
        mirror happened to be listed twice.
        """
        materialized = tuple(arms)
        if not materialized:
            raise ConfigurationError(
                "At least one mirror is required to route between",
                parameter="arms",
                value=arms,
            )
        seen = set()
        for arm in materialized:
            if not isinstance(arm, str) or not arm:
                raise ConfigurationError(
                    f"Mirror identifiers must be non-empty strings, got {arm!r}",
                    parameter="arms",
                    value=arm,
                )
            if arm in seen:
                raise ConfigurationError(
                    f"Duplicate mirror identifier {arm!r}",
                    parameter="arms",
                    value=arm,
                )
            seen.add(arm)
        return materialized

    @property
    def arms(self) -> Tuple[str, ...]:
        """Mirrors being routed between, in their configured order."""
        return self._arms

    @property
    def arm_count(self) -> int:
        """Number of mirrors, the M of the formulation."""
        return len(self._arms)

    @property
    def exploration_rate(self) -> float:
        """Uniform probability mass reserved for exploration, the eta."""
        return self._eta

    @property
    def weight_decay(self) -> float:
        """Per-round pull toward the mean; zero is classic EXP3."""
        return self._decay

    @property
    def rounds(self) -> int:
        """Number of updates absorbed so far."""
        return self._rounds

    @property
    def min_probability(self) -> float:
        """
        Floor on any arm's selection probability.

        The reciprocal caps the importance weight, which is what keeps the
        reward estimator bounded.
        """
        return self._eta / self.arm_count

    @property
    def max_log_weight_delta(self) -> float:
        """
        Largest log-weight increment a single round can produce.

        Equals 1.0 for any configuration: r <= 1 and p >= eta/M bound r_hat by
        M/eta, so eta * r_hat / M <= 1 regardless of how eta and M are chosen.
        """
        return self._eta * (1.0 / self.min_probability) / self.arm_count

    def _distribution_locked(self) -> List[float]:
        """
        Mix the weight-proportional distribution with the uniform floor.

        Computed as a softmax over log weights, so no weight is ever
        exponentiated into a range where it could overflow.
        """
        total = _logsumexp(self._log_weights)
        uniform = self._eta / self.arm_count
        if total == _LOG_ZERO:
            # Every weight has decayed to zero; fall back to uniform rather
            # than dividing by nothing.
            return [1.0 / self.arm_count] * self.arm_count
        return [
            (1.0 - self._eta) * math.exp(log_weight - total) + uniform
            for log_weight in self._log_weights
        ]

    def probabilities(self) -> Dict[str, float]:
        """Current selection distribution over mirrors, summing to 1."""
        with self._lock:
            return dict(zip(self._arms, self._distribution_locked()))

    def probability(self, arm: str) -> float:
        """Current selection probability of one mirror."""
        with self._lock:
            return self._distribution_locked()[self._require_arm(arm)]

    def weights(self) -> Dict[str, float]:
        """
        Weights normalized to sum to 1, for observability.

        The raw log weights are an implementation detail whose absolute scale is
        arbitrary after rescaling; the normalized form is what carries meaning.
        """
        with self._lock:
            total = _logsumexp(self._log_weights)
            if total == _LOG_ZERO:
                return {arm: 0.0 for arm in self._arms}
            return {
                arm: math.exp(log_weight - total)
                for arm, log_weight in zip(self._arms, self._log_weights)
            }

    def log_weights(self) -> Dict[str, float]:
        """Raw log weights, exposed for state persistence and diagnostics."""
        with self._lock:
            return dict(zip(self._arms, self._log_weights))

    def _require_arm(self, arm: str) -> int:
        """Resolve a mirror identifier to its position, or raise."""
        position = self._index.get(arm)
        if position is None:
            raise ConfigurationError(
                f"Unknown mirror {arm!r}; known mirrors are {list(self._arms)}",
                parameter="arm",
                value=arm,
            )
        return position

    def select(self) -> ArmSelection:
        """
        Draw a mirror from the current distribution.

        Returns the probability alongside the arm so the reward can be scaled by
        the distribution that actually produced the draw, however long it takes
        to arrive.
        """
        with self._lock:
            return self._draw_locked(list(range(self.arm_count)))

    def select_from(self, candidates: Sequence[str]) -> ArmSelection:
        """
        Draw from a restricted set of mirrors, renormalized over the survivors.

        Needed because mirrors come and go mid-transfer: a circuit-broken edge
        must not be selected however much weight it still carries. Restricting
        the draw rather than zeroing the weight keeps the blacklisted mirror's
        learned standing intact for when it returns.

        The reported probability is the *conditional* one, p_i / sum over the
        candidates, because that is the distribution the draw was actually
        made from and r/p is unbiased only against the distribution that
        produced the action. Conditioning can only raise a probability, so the
        importance weight stays bounded by the same M / eta as before.

        This makes the algorithm EXP3 over a time-varying action set, and the
        guarantee weakens accordingly: regret is measured against the best
        mirror *available at the time*, not the best overall. That is the right
        target anyway, since a blacklisted mirror is not a choice the router
        could have made.

        Raises:
            ConfigurationError: If the candidate set is empty or names an
                unknown mirror.
        """
        if not candidates:
            raise ConfigurationError(
                "At least one candidate mirror is required to select from; "
                "an empty pool is a caller-side wait condition, not a draw",
                parameter="candidates",
                value=candidates,
            )
        with self._lock:
            positions: List[int] = []
            seen = set()
            for arm in candidates:
                position = self._require_arm(arm)
                if position not in seen:
                    seen.add(position)
                    positions.append(position)
            return self._draw_locked(positions)

    def _draw_locked(self, positions: List[int]) -> ArmSelection:
        """
        Sample one arm from the given positions, renormalized over them.

        Shared by the full and restricted draws so there is a single sampling
        path: the distribution is built once, conditioned on the candidate set,
        and the probability reported is the one the draw used.
        """
        distribution = self._distribution_locked()
        mass = sum(distribution[position] for position in positions)
        if mass <= 0.0:
            # Unreachable while the uniform floor holds, since every arm keeps
            # at least eta/M. Falling back to a uniform draw over the
            # candidates is the only sane response if it ever does not.
            weights = [1.0 / len(positions)] * len(positions)
        else:
            weights = [distribution[position] / mass for position in positions]

        target = self._random.random()
        cumulative = 0.0
        chosen = len(positions) - 1
        for offset, weight in enumerate(weights):
            cumulative += weight
            if target < cumulative:
                chosen = offset
                break
        # Falling through to the last candidate covers the case where
        # accumulated floating-point error leaves the total a hair below 1.0.
        position = positions[chosen]
        return ArmSelection(
            arm=self._arms[position],
            probability=weights[chosen],
            round_index=self._rounds,
        )

    def update(self, selection: ArmSelection, reward: float) -> WeightUpdate:
        """
        Absorb the reward observed for a previously selected mirror.

        Raises:
            ConfigurationError: If the arm is unknown or the reward is outside [0, 1].
        """
        return self.update_arm(selection.arm, reward, selection.probability)

    def update_arm(self, arm: str, reward: float, probability: float) -> WeightUpdate:
        """
        Absorb a reward given the arm and the probability it was drawn with.

        The primitive form, for callers that persist the selection across a
        process boundary rather than holding the ArmSelection object.

        Raises:
            ConfigurationError: If the arm is unknown, the reward lies outside
                [0, 1], or the probability is not a valid selection probability.
        """
        position = self._require_arm(arm)
        normalized_reward = self._validate_reward(reward)

        if isinstance(probability, bool) or not isinstance(probability, (int, float)):
            raise ConfigurationError(
                f"probability must be numeric, got {type(probability).__name__}",
                parameter="probability",
                value=probability,
            )
        numeric_probability = float(probability)
        if not math.isfinite(numeric_probability) or not (
            0.0 < numeric_probability <= 1.0
        ):
            raise ConfigurationError(
                f"probability must lie in (0, 1], got {probability}",
                parameter="probability",
                value=probability,
            )

        with self._lock:
            estimated = normalized_reward / numeric_probability
            delta = self._eta * estimated / self.arm_count
            self._log_weights[position] += delta

            if self._decay > 0.0:
                self._apply_decay_locked()

            self._rescale_locked()
            self._rounds += 1

            return WeightUpdate(
                arm=arm,
                reward=normalized_reward,
                probability=numeric_probability,
                estimated_reward=estimated,
                log_weight_delta=delta,
                round_index=self._rounds - 1,
            )

    @staticmethod
    def _validate_reward(reward: float) -> float:
        """
        Validate that a reward is a finite number in [0, 1].

        The bound is not cosmetic: the guarantee that a single update cannot
        move a log weight by more than 1 rests on r <= 1, and an unnormalized
        throughput in bytes per second would move it by billions and erase every
        other mirror in one round.
        """
        if isinstance(reward, bool) or not isinstance(reward, (int, float)):
            raise ConfigurationError(
                f"reward must be numeric, got {type(reward).__name__}",
                parameter="reward",
                value=reward,
            )
        numeric = float(reward)
        if not math.isfinite(numeric) or not 0.0 <= numeric <= 1.0:
            raise ConfigurationError(
                f"reward must be a finite value in [0, 1], got {reward}",
                parameter="reward",
                value=reward,
            )
        return numeric

    def _apply_decay_locked(self) -> None:
        """
        Mix every weight toward the mean, bounding the router's memory.

        The EXP3.S step, carried out entirely in log space:

            w_m <- (1 - alpha) * w_m + (alpha / M) * sum_j w_j
        """
        total = _logsumexp(self._log_weights)
        if total == _LOG_ZERO:
            return
        keep = math.log1p(-self._decay) if self._decay < 1.0 else _LOG_ZERO
        share = math.log(self._decay / self.arm_count) + total
        self._log_weights = [
            _logaddexp(keep + log_weight, share) for log_weight in self._log_weights
        ]

    def _rescale_locked(self) -> None:
        """
        Shift the log weights so the largest is exactly zero.

        The selection distribution depends only on ratios between weights, so a
        common shift leaves it exactly unchanged.

        This is hygiene rather than a correctness requirement, and worth being
        precise about. Every exponential in this module is taken of a
        *difference* — against the log-sum in the distribution, against the
        larger term in _logaddexp — so the distribution stays valid even with
        the raw weights left to drift; disabling this and running 200000
        rounds leaves a log weight at 200000 and the probabilities still exact.
        What it buys is bounded stored magnitudes: serialized state stays small
        and readable, absolute precision does not erode as the exponent grows,
        and no future code path can exponentiate a raw weight by accident.
        """
        highest = max(self._log_weights)
        if highest == _LOG_ZERO or highest == 0.0:
            return
        self._log_weights = [
            log_weight - highest for log_weight in self._log_weights
        ]

    def reset(self) -> None:
        """Return every mirror to the uniform prior."""
        with self._lock:
            self._log_weights = [0.0] * self.arm_count
            self._rounds = 0

    def best_arm(self) -> str:
        """
        Mirror currently carrying the most weight.

        Reports the router's belief; it is not what ``select`` returns, which
        samples so that weaker mirrors keep being tested.
        """
        with self._lock:
            best = max(range(self.arm_count), key=lambda i: self._log_weights[i])
            return self._arms[best]

    def to_dict(self) -> Dict[str, object]:
        """
        Serialize the router for crash-resilient resume.

        Log weights are persisted directly. Their absolute scale is arbitrary
        after rescaling but the differences between them are the learned state,
        so they must be stored together and restored as a set.
        """
        with self._lock:
            return {
                "arms": list(self._arms),
                "log_weights": list(self._log_weights),
                "exploration_rate": self._eta,
                "weight_decay": self._decay,
                "rounds": self._rounds,
            }

    @classmethod
    def from_dict(
        cls, data: Dict[str, object], seed: Optional[int] = None
    ) -> "EXP3Bandit":
        """
        Restore a router from its serialized form.

        Raises:
            ConfigurationError: If a required key is missing or the stored
                weight vector does not match the stored mirror set.
        """
        for key in ("arms", "log_weights", "exploration_rate", "weight_decay"):
            if key not in data:
                raise ConfigurationError(
                    f"Serialized bandit is missing required key '{key}'",
                    parameter=key,
                    value=data,
                )
        arms = data["arms"]
        log_weights = data["log_weights"]
        if not isinstance(arms, (list, tuple)) or not isinstance(
            log_weights, (list, tuple)
        ):
            raise ConfigurationError(
                "Serialized 'arms' and 'log_weights' must both be sequences",
                parameter="arms",
                value=data,
            )
        if len(arms) != len(log_weights):
            raise ConfigurationError(
                f"Serialized bandit has {len(arms)} mirrors but "
                f"{len(log_weights)} weights",
                parameter="log_weights",
                value=data,
            )

        bandit = cls(
            arms=list(arms),
            exploration_rate=float(data["exploration_rate"]),  # type: ignore[arg-type]
            weight_decay=float(data["weight_decay"]),  # type: ignore[arg-type]
            seed=seed,
        )
        restored: List[float] = []
        for weight in log_weights:
            if isinstance(weight, bool) or not isinstance(weight, (int, float)):
                raise ConfigurationError(
                    f"Serialized log weight must be numeric, got {weight!r}",
                    parameter="log_weights",
                    value=weight,
                )
            numeric = float(weight)
            if math.isnan(numeric) or numeric == math.inf:
                raise ConfigurationError(
                    f"Serialized log weight must be finite or -inf, got {weight!r}",
                    parameter="log_weights",
                    value=weight,
                )
            restored.append(numeric)

        with bandit._lock:
            bandit._log_weights = restored
            bandit._rescale_locked()
            bandit._rounds = int(data.get("rounds", 0))  # type: ignore[call-overload]
        return bandit

    def __repr__(self) -> str:
        return (
            f"EXP3Bandit(arms={len(self._arms)}, eta={self._eta}, "
            f"decay={self._decay}, rounds={self._rounds})"
        )


# ---------------------------------------------------------------------------
# Mirror health and reward calculation
# ---------------------------------------------------------------------------
#
# EXP3 consumes a scalar reward in [0, 1] and says nothing about where it comes
# from. Supplying it is this half of the module, and the normalization is the
# whole difficulty: throughput is an unbounded quantity in bytes per second and
# the bandit needs a bounded one.
#
#     r = (Throughput / PeakThroughput) * (1 - error_flag)
#
# The peak is tracked across the whole mirror pool rather than per mirror,
# because the rewards have to be comparable between arms for the comparison to
# mean anything. Normalizing each mirror against its own historical best would
# score every mirror near 1 whenever it performed typically for itself, and a
# uniformly mediocre edge would look identical to a fast one.
#
# An error scores zero rather than a small value. EXP3 needs no penalty term
# because exp(0) = 1 leaves the weight untouched while every competing mirror's
# weight climbs past it, so a failing mirror is demoted by everyone else's
# success rather than by an explicit punishment.
#
# Repeated failures are a different problem from low reward, and the bandit
# alone handles them badly. A mirror returning connection errors still holds the
# eta/M exploration floor, so a dead edge would keep drawing its share of
# requests forever — each one costing a connection timeout. The circuit breaker
# removes it from the pool outright, then lets it back after a cooldown so a
# recovered edge is not blacklisted permanently.


# Consecutive failures before a mirror is removed from the pool. Consecutive
# rather than cumulative: an edge that fails one request in fifty is degraded
# but usable, while three in a row is a mirror that is down.
DEFAULT_FAILURE_THRESHOLD = 3

# Seconds a mirror stays blacklisted before a trial request is allowed.
DEFAULT_COOLDOWN_SECONDS = 30.0

# Multiplier applied to the cooldown each time a trial fails again, so a
# persistently dead mirror is retried with decreasing frequency instead of
# being probed every cooldown forever.
DEFAULT_BACKOFF_MULTIPLIER = 2.0

# Ceiling on the backed-off cooldown. Without it an outage lasting hours would
# push the retry interval past the length of any plausible transfer, and the
# mirror would never be reconsidered even after recovering.
DEFAULT_MAX_COOLDOWN_SECONDS = 300.0

# Per-observation decay applied to the peak throughput. A single spuriously
# fast sample — a small range served from cache, or one whose duration rounds
# toward the clock's resolution — would otherwise depress every subsequent
# reward for the rest of the transfer. Decaying the peak lets such an outlier
# fade while a genuinely fast mirror keeps re-establishing it.
DEFAULT_PEAK_DECAY = 0.01

# Smallest transfer whose throughput is allowed to set a new peak. Short
# transfers are dominated by connection setup and timer granularity, so their
# apparent rate is unreliable in both directions.
DEFAULT_MIN_PEAK_SAMPLE_BYTES = 64 * 1024


class CircuitState(str, Enum):
    """Availability state of one mirror."""

    # Healthy: requests flow normally.
    CLOSED = "CLOSED"

    # Blacklisted after consecutive failures; no requests are issued.
    OPEN = "OPEN"

    # Cooldown elapsed; a trial request is allowed to test for recovery.
    HALF_OPEN = "HALF_OPEN"


@dataclass(frozen=True)
class MirrorReward:
    """
    The reward for one completed request, with the terms that produced it.

    Retains the raw throughput and the peak it was normalized against, because
    a reward of 0.2 is uninterpretable on its own — it could mean a slow mirror
    or a fast one measured against an inflated peak.

    Attributes:
        mirror: Mirror the request was issued to.
        reward: Normalized reward in [0, 1], ready for the bandit.
        throughput_bps: Observed throughput in bytes per second.
        peak_bps: Pool-wide peak the observation was normalized against.
        errored: Whether the request failed.
        circuit_state: The mirror's availability after this observation.
    """

    mirror: str
    reward: float
    throughput_bps: float
    peak_bps: float
    errored: bool
    circuit_state: CircuitState

    def __repr__(self) -> str:
        return (
            f"MirrorReward(mirror={self.mirror!r}, reward={self.reward:.4f}, "
            f"throughput={self.throughput_bps:.0f}B/s, "
            f"errored={self.errored}, circuit={self.circuit_state.value})"
        )


class CircuitBreaker:
    """
    Removes a repeatedly failing mirror from the pool, then lets it back.

    Three states rather than two. A blacklisted mirror cannot be restored by
    evidence, because while it is blacklisted no requests are issued to it and
    no evidence can arrive; the half-open state is what breaks that deadlock by
    admitting one trial request to find out.

    Time is injected rather than read from a module-level clock so recovery
    after a cooldown can be tested without sleeping through it.
    """

    def __init__(
        self,
        failure_threshold: int = DEFAULT_FAILURE_THRESHOLD,
        cooldown_seconds: float = DEFAULT_COOLDOWN_SECONDS,
        backoff_multiplier: float = DEFAULT_BACKOFF_MULTIPLIER,
        max_cooldown_seconds: Optional[float] = None,
        clock: Optional[Callable[[], float]] = None,
    ) -> None:
        if isinstance(failure_threshold, bool) or not isinstance(
            failure_threshold, int
        ):
            raise ConfigurationError(
                "failure_threshold must be an integer, got "
                f"{type(failure_threshold).__name__}",
                parameter="failure_threshold",
                value=failure_threshold,
            )
        if failure_threshold < 1:
            raise ConfigurationError(
                f"failure_threshold must be at least 1, got {failure_threshold}",
                parameter="failure_threshold",
                value=failure_threshold,
            )
        self._threshold = failure_threshold
        self._base_cooldown = _validate_positive_seconds(
            cooldown_seconds, "cooldown_seconds"
        )
        # Defaulting the cap relative to the base rather than to a constant:
        # a caller who sets only a long cooldown means it, and should not have
        # to discover a separate ceiling to make their own setting legal. An
        # explicitly conflicting pair is still an error.
        self._max_cooldown = _validate_positive_seconds(
            max(DEFAULT_MAX_COOLDOWN_SECONDS, self._base_cooldown)
            if max_cooldown_seconds is None
            else max_cooldown_seconds,
            "max_cooldown_seconds",
        )
        if self._max_cooldown < self._base_cooldown:
            raise ConfigurationError(
                f"max_cooldown_seconds ({max_cooldown_seconds}) must be at least "
                f"cooldown_seconds ({cooldown_seconds})",
                parameter="max_cooldown_seconds",
                value=max_cooldown_seconds,
            )
        if isinstance(backoff_multiplier, bool) or not isinstance(
            backoff_multiplier, (int, float)
        ):
            raise ConfigurationError(
                "backoff_multiplier must be numeric, got "
                f"{type(backoff_multiplier).__name__}",
                parameter="backoff_multiplier",
                value=backoff_multiplier,
            )
        if not math.isfinite(float(backoff_multiplier)) or backoff_multiplier < 1.0:
            raise ConfigurationError(
                "backoff_multiplier must be a finite number of at least 1, got "
                f"{backoff_multiplier}",
                parameter="backoff_multiplier",
                value=backoff_multiplier,
            )

        self._backoff = float(backoff_multiplier)
        self._clock = clock if clock is not None else time.monotonic
        self._consecutive_failures = 0
        self._opened_at: Optional[float] = None
        self._current_cooldown = self._base_cooldown
        self._trips = 0

    @property
    def failure_threshold(self) -> int:
        """Consecutive failures that trip the breaker."""
        return self._threshold

    @property
    def cooldown_seconds(self) -> float:
        """Cooldown currently in force, after any backoff."""
        return self._current_cooldown

    @property
    def consecutive_failures(self) -> int:
        """Failures since the last success."""
        return self._consecutive_failures

    @property
    def trips(self) -> int:
        """Number of times the breaker has opened."""
        return self._trips

    @property
    def state(self) -> CircuitState:
        """
        Current availability, promoting to half-open once the cooldown elapses.

        Derived from the clock rather than stored, so no timer has to fire for a
        mirror to become eligible again.
        """
        if self._opened_at is None:
            return CircuitState.CLOSED
        if self._clock() - self._opened_at >= self._current_cooldown:
            return CircuitState.HALF_OPEN
        return CircuitState.OPEN

    @property
    def is_available(self) -> bool:
        """Whether a request may be issued to this mirror."""
        return self.state is not CircuitState.OPEN

    @property
    def seconds_until_retry(self) -> float:
        """Seconds remaining before a trial request is permitted; 0 if available."""
        if self._opened_at is None:
            return 0.0
        remaining = self._current_cooldown - (self._clock() - self._opened_at)
        return max(0.0, remaining)

    def record_success(self) -> CircuitState:
        """
        Register a successful request, closing the breaker.

        Resets the backoff as well as the failure count: a mirror that has
        served a request is healthy now, and holding a long cooldown against it
        would punish it for an outage it has recovered from.
        """
        self._consecutive_failures = 0
        self._opened_at = None
        self._current_cooldown = self._base_cooldown
        return CircuitState.CLOSED

    def record_failure(self) -> CircuitState:
        """
        Register a failed request, opening the breaker once the threshold is met.

        A failure while half-open reopens immediately regardless of the count,
        since the trial request existed precisely to answer whether the mirror
        had recovered, and it answered no.
        """
        was_half_open = self.state is CircuitState.HALF_OPEN
        self._consecutive_failures += 1

        if was_half_open:
            self._current_cooldown = min(
                self._max_cooldown, self._current_cooldown * self._backoff
            )
            self._opened_at = self._clock()
            self._trips += 1
            return self.state

        if self._consecutive_failures >= self._threshold and self._opened_at is None:
            self._opened_at = self._clock()
            self._trips += 1
        return self.state

    def reset(self) -> None:
        """Return the breaker to its initial closed state."""
        self._consecutive_failures = 0
        self._opened_at = None
        self._current_cooldown = self._base_cooldown
        self._trips = 0

    def __repr__(self) -> str:
        return (
            f"CircuitBreaker(state={self.state.value}, "
            f"consecutive_failures={self._consecutive_failures}, "
            f"cooldown={self._current_cooldown}s)"
        )


def _validate_positive_seconds(value: float, parameter: str) -> float:
    """
    Validate a duration in seconds.

    Raises:
        ConfigurationError: If the value is non-numeric, non-finite, or <= 0.
    """
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ConfigurationError(
            f"{parameter} must be numeric, got {type(value).__name__}",
            parameter=parameter,
            value=value,
        )
    numeric = float(value)
    if not math.isfinite(numeric) or numeric <= 0.0:
        raise ConfigurationError(
            f"{parameter} must be a positive finite number of seconds, got {value}",
            parameter=parameter,
            value=value,
        )
    return numeric


@dataclass(frozen=True)
class MirrorStats:
    """
    Point-in-time health summary for one mirror.

    Attributes:
        mirror: Mirror identifier.
        state: Current circuit state.
        successes: Successful requests observed.
        failures: Failed requests observed.
        consecutive_failures: Failures since the last success.
        trips: Times the breaker has opened.
        last_throughput_bps: Throughput of the most recent successful request.
        last_reward: Most recent reward handed to the bandit.
        seconds_until_retry: Time before a blacklisted mirror may be retried.
    """

    mirror: str
    state: CircuitState
    successes: int
    failures: int
    consecutive_failures: int
    trips: int
    last_throughput_bps: float
    last_reward: float
    seconds_until_retry: float

    @property
    def total_requests(self) -> int:
        """Requests observed for this mirror."""
        return self.successes + self.failures

    @property
    def success_ratio(self) -> float:
        """Fraction of observed requests that succeeded; 1.0 before any."""
        if self.total_requests == 0:
            return 1.0
        return self.successes / self.total_requests

    @property
    def is_available(self) -> bool:
        """Whether a request may currently be issued to this mirror."""
        return self.state is not CircuitState.OPEN


class MirrorHealthMonitor:
    """
    Turns completed requests into bandit rewards and keeps dead mirrors out.

    Holds the pool-wide throughput peak that normalizes every reward, so all
    mirrors are scored on one scale, and one circuit breaker per mirror.

    Thread-safe: a download engine reports completions from many workers at
    once, and the peak is shared mutable state.
    """

    def __init__(
        self,
        mirrors: Sequence[str],
        failure_threshold: int = DEFAULT_FAILURE_THRESHOLD,
        cooldown_seconds: float = DEFAULT_COOLDOWN_SECONDS,
        backoff_multiplier: float = DEFAULT_BACKOFF_MULTIPLIER,
        max_cooldown_seconds: Optional[float] = None,
        peak_decay: float = DEFAULT_PEAK_DECAY,
        min_peak_sample_bytes: int = DEFAULT_MIN_PEAK_SAMPLE_BYTES,
        clock: Optional[Callable[[], float]] = None,
    ) -> None:
        self._mirrors = EXP3Bandit._validate_arms(mirrors)
        self._peak_decay = _validate_unit_interval(
            peak_decay, "peak_decay", allow_zero=True
        )
        if isinstance(min_peak_sample_bytes, bool) or not isinstance(
            min_peak_sample_bytes, int
        ):
            raise ConfigurationError(
                "min_peak_sample_bytes must be an integer, got "
                f"{type(min_peak_sample_bytes).__name__}",
                parameter="min_peak_sample_bytes",
                value=min_peak_sample_bytes,
            )
        if min_peak_sample_bytes < 0:
            raise ConfigurationError(
                "min_peak_sample_bytes must be non-negative, got "
                f"{min_peak_sample_bytes}",
                parameter="min_peak_sample_bytes",
                value=min_peak_sample_bytes,
            )

        self._min_peak_bytes = min_peak_sample_bytes
        self._breakers: Dict[str, CircuitBreaker] = {
            mirror: CircuitBreaker(
                failure_threshold=failure_threshold,
                cooldown_seconds=cooldown_seconds,
                backoff_multiplier=backoff_multiplier,
                max_cooldown_seconds=max_cooldown_seconds,
                clock=clock,
            )
            for mirror in self._mirrors
        }
        self._successes: Dict[str, int] = {m: 0 for m in self._mirrors}
        self._failures: Dict[str, int] = {m: 0 for m in self._mirrors}
        self._last_throughput: Dict[str, float] = {m: 0.0 for m in self._mirrors}
        self._last_reward: Dict[str, float] = {m: 0.0 for m in self._mirrors}
        self._peak_bps = 0.0
        self._lock = threading.RLock()

    @property
    def mirrors(self) -> Tuple[str, ...]:
        """Mirrors being monitored."""
        return self._mirrors

    @property
    def peak_throughput_bps(self) -> float:
        """Pool-wide peak every reward is normalized against."""
        with self._lock:
            return self._peak_bps

    def _require_mirror(self, mirror: str) -> str:
        """Validate that a mirror belongs to the monitored pool."""
        if mirror not in self._breakers:
            raise ConfigurationError(
                f"Unknown mirror {mirror!r}; known mirrors are {list(self._mirrors)}",
                parameter="mirror",
                value=mirror,
            )
        return mirror

    def breaker(self, mirror: str) -> CircuitBreaker:
        """Circuit breaker guarding one mirror."""
        return self._breakers[self._require_mirror(mirror)]

    def is_available(self, mirror: str) -> bool:
        """Whether a request may be issued to one mirror."""
        return self.breaker(mirror).is_available

    def available_mirrors(self) -> Tuple[str, ...]:
        """
        Mirrors currently eligible for requests, in pool order.

        Empty when every mirror is blacklisted, which the caller must handle:
        the right response is to wait for the soonest cooldown rather than to
        fail the transfer, since the breakers reopen on their own.
        """
        with self._lock:
            return tuple(
                mirror
                for mirror in self._mirrors
                if self._breakers[mirror].is_available
            )

    def seconds_until_any_available(self) -> float:
        """
        Time until at least one mirror may be retried; 0 if one is available now.

        Lets a caller facing a fully blacklisted pool sleep exactly as long as
        needed instead of polling.
        """
        with self._lock:
            if any(b.is_available for b in self._breakers.values()):
                return 0.0
            return min(b.seconds_until_retry for b in self._breakers.values())

    def _update_peak_locked(self, throughput: float, transferred: int) -> None:
        """
        Fold an observation into the pool-wide peak.

        The peak decays a little on every observation so a single spuriously
        fast sample fades rather than depressing every later reward for the rest
        of the transfer. A genuinely fast mirror re-establishes it continuously,
        so the decay costs nothing while the mirror keeps performing.
        """
        if self._peak_decay > 0.0:
            self._peak_bps *= 1.0 - self._peak_decay
        if transferred >= self._min_peak_bytes and throughput > self._peak_bps:
            self._peak_bps = throughput

    def record_transfer(
        self,
        mirror: str,
        bytes_transferred: int,
        duration_seconds: float,
        success: bool = True,
    ) -> MirrorReward:
        """
        Record a completed request and compute its reward.

        Raises:
            ConfigurationError: If the mirror is unknown, the byte count is
                negative, or the duration is not a positive finite number.
        """
        self._require_mirror(mirror)
        if isinstance(bytes_transferred, bool) or not isinstance(
            bytes_transferred, int
        ):
            raise ConfigurationError(
                "bytes_transferred must be an integer, got "
                f"{type(bytes_transferred).__name__}",
                parameter="bytes_transferred",
                value=bytes_transferred,
            )
        if bytes_transferred < 0:
            raise ConfigurationError(
                f"bytes_transferred must be non-negative, got {bytes_transferred}",
                parameter="bytes_transferred",
                value=bytes_transferred,
            )
        duration = _validate_positive_seconds(duration_seconds, "duration_seconds")

        if not success:
            return self.record_failure(mirror)

        throughput = bytes_transferred / duration
        with self._lock:
            self._update_peak_locked(throughput, bytes_transferred)
            # The peak is the maximum observed, so the ratio cannot exceed 1;
            # min() guards the case where this very sample was excluded from the
            # peak for being too short to measure reliably.
            reward = 0.0 if self._peak_bps <= 0.0 else min(
                1.0, throughput / self._peak_bps
            )

            self._successes[mirror] += 1
            self._last_throughput[mirror] = throughput
            self._last_reward[mirror] = reward
            state = self._breakers[mirror].record_success()

            return MirrorReward(
                mirror=mirror,
                reward=reward,
                throughput_bps=throughput,
                peak_bps=self._peak_bps,
                errored=False,
                circuit_state=state,
            )

    def record_failure(self, mirror: str) -> MirrorReward:
        """
        Record a failed request, scoring zero and advancing the breaker.

        Zero rather than a small value: EXP3 needs no penalty term, since
        exp(0) leaves the weight untouched while every competing mirror climbs
        past it.
        """
        self._require_mirror(mirror)
        with self._lock:
            self._failures[mirror] += 1
            self._last_reward[mirror] = 0.0
            state = self._breakers[mirror].record_failure()
            return MirrorReward(
                mirror=mirror,
                reward=0.0,
                throughput_bps=0.0,
                peak_bps=self._peak_bps,
                errored=True,
                circuit_state=state,
            )

    def stats(self, mirror: str) -> MirrorStats:
        """Health summary for one mirror."""
        self._require_mirror(mirror)
        with self._lock:
            breaker = self._breakers[mirror]
            return MirrorStats(
                mirror=mirror,
                state=breaker.state,
                successes=self._successes[mirror],
                failures=self._failures[mirror],
                consecutive_failures=breaker.consecutive_failures,
                trips=breaker.trips,
                last_throughput_bps=self._last_throughput[mirror],
                last_reward=self._last_reward[mirror],
                seconds_until_retry=breaker.seconds_until_retry,
            )

    def all_stats(self) -> Dict[str, MirrorStats]:
        """Health summaries for every monitored mirror."""
        return {mirror: self.stats(mirror) for mirror in self._mirrors}

    def reset(self) -> None:
        """Clear all health history and the pool-wide peak."""
        with self._lock:
            for mirror in self._mirrors:
                self._breakers[mirror].reset()
                self._successes[mirror] = 0
                self._failures[mirror] = 0
                self._last_throughput[mirror] = 0.0
                self._last_reward[mirror] = 0.0
            self._peak_bps = 0.0

    def __repr__(self) -> str:
        return (
            f"MirrorHealthMonitor(mirrors={len(self._mirrors)}, "
            f"available={len(self.available_mirrors())}, "
            f"peak={self._peak_bps:.0f}B/s)"
        )


# ---------------------------------------------------------------------------
# Worker request dispatch
# ---------------------------------------------------------------------------
#
# The two halves above answer different questions and neither is usable alone.
# The bandit knows which mirror deserves the next request but not which mirrors
# are reachable; the health monitor knows which are reachable and how well they
# performed but has no opinion on which to pick. The dispatcher joins them into
# the loop a download worker actually runs:
#
#     dispatch  -> pick an available mirror, resolve its URL, hand back a handle
#     (worker issues the range request)
#     complete  -> score the transfer, update the weights, close the loop
#
# The handle is what makes the loop correct under concurrency. A worker pool has
# many requests outstanding at once and they finish out of order, so the
# selection probability, the mirror and the start time all have to travel with
# the individual request rather than live in the dispatcher. Reconstructing any
# of them at completion time would read state that a dozen other completions
# have since moved.
#
# Selection is restricted to mirrors whose breaker is closed or half-open,
# conditioned rather than filtered after the fact, so a blacklisted mirror is
# never drawn and never has to be redrawn. An exhausted pool is not an error:
# every breaker reopens on its own, so the dispatcher reports how long to wait
# instead of failing a transfer that will be servable again shortly.


@dataclass(frozen=True)
class MirrorEndpoint:
    """
    One mirror in the pool: a stable identifier and the URL to fetch from.

    Identifier and URL are kept separate so the bandit's learned weights survive
    a URL change — a redirected edge or a rotated hostname is the same mirror,
    and restarting its learning because its address moved would discard exactly
    the evidence that makes routing work.

    Attributes:
        mirror_id: Stable identifier used as the bandit arm.
        url: Absolute URL the file is fetched from on this mirror.
    """

    mirror_id: str
    url: str

    def __post_init__(self) -> None:
        if not isinstance(self.mirror_id, str) or not self.mirror_id:
            raise ConfigurationError(
                "mirror_id must be a non-empty string",
                parameter="mirror_id",
                value=self.mirror_id,
            )
        if not isinstance(self.url, str) or not self.url:
            raise ConfigurationError(
                f"url for mirror {self.mirror_id!r} must be a non-empty string",
                parameter="url",
                value=self.url,
            )

    @classmethod
    def from_url(cls, url: str) -> "MirrorEndpoint":
        """Build an endpoint whose identifier is the URL itself."""
        return cls(mirror_id=url, url=url)


@dataclass(frozen=True)
class DispatchedRequest:
    """
    A handle for one in-flight range request.

    Carries everything the completion needs, because by the time a reward
    arrives the dispatcher's state has moved on. In particular it carries the
    selection, whose probability is the one the draw was made from; recomputing
    it at completion time would bias every estimate in flight.

    Attributes:
        request_id: Monotonic identifier, unique within a dispatcher.
        mirror: Mirror the request was routed to.
        url: Resolved URL for the request.
        selection: The bandit draw that chose this mirror.
        chunk: Range being fetched, if the caller supplied one.
        started_at: Clock reading when the request was dispatched.
    """

    request_id: int
    mirror: str
    url: str
    selection: ArmSelection
    chunk: Optional[ChunkSpec]
    started_at: float

    @property
    def range_header(self) -> Optional[str]:
        """HTTP Range header for this request, if a chunk was supplied."""
        return None if self.chunk is None else self.chunk.range_header_value

    @property
    def expected_bytes(self) -> Optional[int]:
        """Byte count the request should return, if a chunk was supplied."""
        return None if self.chunk is None else self.chunk.size

    def __repr__(self) -> str:
        return (
            f"DispatchedRequest(id={self.request_id}, mirror={self.mirror!r}, "
            f"range={self.range_header}, p={self.selection.probability:.4f})"
        )


@dataclass(frozen=True)
class DispatchOutcome:
    """
    The closed loop for one request: what happened, and what it taught.

    Attributes:
        request: The handle that was completed.
        reward: Normalized reward the transfer earned.
        update: Weight update the reward produced.
        bytes_transferred: Bytes actually received.
        duration_seconds: Wall-clock time the request took.
        success: Whether the request succeeded.
    """

    request: DispatchedRequest
    reward: MirrorReward
    update: WeightUpdate
    bytes_transferred: int
    duration_seconds: float
    success: bool

    @property
    def mirror(self) -> str:
        """Mirror the request was routed to."""
        return self.request.mirror

    @property
    def throughput_bps(self) -> float:
        """Observed throughput for this request."""
        return self.reward.throughput_bps

    @property
    def circuit_state(self) -> CircuitState:
        """Mirror's availability after this outcome."""
        return self.reward.circuit_state

    def __repr__(self) -> str:
        return (
            f"DispatchOutcome(mirror={self.mirror!r}, success={self.success}, "
            f"bytes={self.bytes_transferred}, "
            f"reward={self.reward.reward:.4f})"
        )


class MirrorDispatcher:
    """
    Routes range requests across a mirror pool and learns from the results.

    Owns an EXP3 router and a health monitor, and is the only object a download
    worker needs to talk to: ``dispatch`` to get a URL, ``complete`` or ``fail``
    to report back.

    Thread-safe. Many workers dispatch and complete concurrently, and requests
    finish out of order.
    """

    def __init__(
        self,
        endpoints: Sequence[MirrorEndpoint],
        exploration_rate: float = DEFAULT_EXPLORATION_RATE,
        weight_decay: float = DEFAULT_WEIGHT_DECAY,
        failure_threshold: int = DEFAULT_FAILURE_THRESHOLD,
        cooldown_seconds: float = DEFAULT_COOLDOWN_SECONDS,
        backoff_multiplier: float = DEFAULT_BACKOFF_MULTIPLIER,
        max_cooldown_seconds: Optional[float] = None,
        peak_decay: float = DEFAULT_PEAK_DECAY,
        clock: Optional[Callable[[], float]] = None,
        seed: Optional[int] = None,
    ) -> None:
        materialized = tuple(endpoints)
        if not materialized:
            raise ConfigurationError(
                "At least one mirror endpoint is required",
                parameter="endpoints",
                value=endpoints,
            )
        for endpoint in materialized:
            if not isinstance(endpoint, MirrorEndpoint):
                raise ConfigurationError(
                    "endpoints must contain MirrorEndpoint instances, got "
                    f"{type(endpoint).__name__}",
                    parameter="endpoints",
                    value=endpoint,
                )

        mirror_ids = [endpoint.mirror_id for endpoint in materialized]
        # Delegated so duplicate identifiers are rejected by the same check the
        # bandit applies, rather than by a second copy that could drift from it.
        EXP3Bandit._validate_arms(mirror_ids)

        self._endpoints = {e.mirror_id: e for e in materialized}
        self._clock = clock if clock is not None else time.monotonic
        self._bandit = EXP3Bandit(
            arms=mirror_ids,
            exploration_rate=exploration_rate,
            weight_decay=weight_decay,
            seed=seed,
        )
        self._monitor = MirrorHealthMonitor(
            mirrors=mirror_ids,
            failure_threshold=failure_threshold,
            cooldown_seconds=cooldown_seconds,
            backoff_multiplier=backoff_multiplier,
            max_cooldown_seconds=max_cooldown_seconds,
            peak_decay=peak_decay,
            clock=self._clock,
        )
        self._next_request_id = 0
        self._in_flight: Dict[int, DispatchedRequest] = {}
        self._dispatched = 0
        self._completed = 0
        self._failed = 0
        self._lock = threading.RLock()

    @property
    def bandit(self) -> EXP3Bandit:
        """Router choosing between mirrors."""
        return self._bandit

    @property
    def monitor(self) -> MirrorHealthMonitor:
        """Health monitor scoring transfers and blacklisting dead mirrors."""
        return self._monitor

    @property
    def mirrors(self) -> Tuple[str, ...]:
        """Mirror identifiers in the pool."""
        return self._bandit.arms

    @property
    def in_flight(self) -> int:
        """Requests dispatched but not yet reported."""
        with self._lock:
            return len(self._in_flight)

    @property
    def seconds_until_retry(self) -> float:
        """Wait before any mirror is usable again; 0 when one is available."""
        return self._monitor.seconds_until_any_available()

    def url_for(self, mirror: str) -> str:
        """
        Resolve a mirror identifier to its URL.

        Raises:
            ConfigurationError: If the mirror is not in the pool.
        """
        endpoint = self._endpoints.get(mirror)
        if endpoint is None:
            raise ConfigurationError(
                f"Unknown mirror {mirror!r}; known mirrors are {list(self.mirrors)}",
                parameter="mirror",
                value=mirror,
            )
        return endpoint.url

    def available_mirrors(
        self, exclude: Sequence[str] = ()
    ) -> Tuple[str, ...]:
        """
        Mirrors eligible for a request, minus any the caller rules out.

        The exclusion is for retries: a chunk whose request just failed should
        be retried somewhere else, and offering the same mirror again would
        usually reproduce the same failure.
        """
        excluded = set(exclude)
        for mirror in excluded:
            self.url_for(mirror)
        return tuple(
            mirror
            for mirror in self._monitor.available_mirrors()
            if mirror not in excluded
        )

    def dispatch(
        self,
        chunk: Optional[ChunkSpec] = None,
        exclude: Sequence[str] = (),
    ) -> Optional[DispatchedRequest]:
        """
        Choose a mirror for the next request and return a handle for it.

        Returns None when no mirror is currently eligible, which is a wait
        condition rather than a failure: every breaker reopens on its own, so
        the caller should sleep for ``seconds_until_retry`` and try again
        instead of abandoning the transfer. Returning None rather than raising
        follows the planner's convention for an expected, recoverable absence.
        """
        with self._lock:
            candidates = self.available_mirrors(exclude=exclude)
            if not candidates:
                return None

            selection = self._bandit.select_from(candidates)
            request = DispatchedRequest(
                request_id=self._next_request_id,
                mirror=selection.arm,
                url=self.url_for(selection.arm),
                selection=selection,
                chunk=chunk,
                started_at=self._clock(),
            )
            self._next_request_id += 1
            self._dispatched += 1
            self._in_flight[request.request_id] = request
            return request

    def _retire_locked(self, request: DispatchedRequest) -> None:
        """
        Remove an in-flight request, rejecting a second report for it.

        A double completion would apply one observation's reward twice, which
        is the kind of bias that produces a plausible-looking distribution
        converging on the wrong mirror.
        """
        if request.request_id not in self._in_flight:
            raise ConfigurationError(
                f"Request {request.request_id} is not in flight; it was already "
                "reported or did not come from this dispatcher",
                parameter="request",
                value=request.request_id,
            )
        del self._in_flight[request.request_id]

    def complete(
        self,
        request: DispatchedRequest,
        bytes_transferred: int,
        duration_seconds: Optional[float] = None,
    ) -> DispatchOutcome:
        """
        Report a successful transfer, scoring it and updating the weights.

        The duration is taken from the dispatcher's clock unless the caller
        supplies one, so a worker that measured the transfer itself can pass a
        figure that excludes queueing it did not want attributed to the mirror.

        Raises:
            ConfigurationError: If the request is not in flight, the byte count
                is invalid, or the elapsed time is not positive.
        """
        with self._lock:
            self._retire_locked(request)
            elapsed = (
                self._elapsed_for(request)
                if duration_seconds is None
                else duration_seconds
            )
            reward = self._monitor.record_transfer(
                request.mirror, bytes_transferred, elapsed, success=True
            )
            update = self._bandit.update(request.selection, reward.reward)
            self._completed += 1
            return DispatchOutcome(
                request=request,
                reward=reward,
                update=update,
                bytes_transferred=bytes_transferred,
                duration_seconds=elapsed,
                success=True,
            )

    def fail(self, request: DispatchedRequest) -> DispatchOutcome:
        """
        Report a failed request, scoring zero and advancing the breaker.

        The bandit update is a no-op on the weights and necessarily so: the
        reward is zero, exp(0) is 1, and no probability can change that. The
        demotion happens the way EXP3 always demotes, by every competing mirror
        climbing past a weight that stood still. What actually removes a failing
        mirror is the breaker, which is why both are called here.

        The update is still applied rather than skipped, because it advances the
        round counter and records the observation with the probability the draw
        was made from, keeping the audit trail complete for a request that did
        happen and did cost time.
        """
        with self._lock:
            self._retire_locked(request)
            elapsed = self._elapsed_for(request)
            reward = self._monitor.record_failure(request.mirror)
            update = self._bandit.update(request.selection, reward.reward)
            self._failed += 1
            return DispatchOutcome(
                request=request,
                reward=reward,
                update=update,
                bytes_transferred=0,
                duration_seconds=elapsed,
                success=False,
            )

    def _elapsed_for(self, request: DispatchedRequest) -> float:
        """
        Time since a request was dispatched, floored above zero.

        A coarse clock can report the same reading twice for a fast transfer;
        the floor keeps the throughput division defined without inventing a
        duration long enough to distort the reward.
        """
        return max(1e-9, self._clock() - request.started_at)

    def abandon(self, request: DispatchedRequest) -> None:
        """
        Drop an in-flight request without scoring it.

        For requests cancelled by the scheduler rather than by the mirror — a
        work-stealing bisection truncating a range, or a shutdown. The mirror
        did nothing wrong and must not be penalized for a decision taken above
        it, so neither the weights nor the breaker are touched.
        """
        with self._lock:
            self._retire_locked(request)

    def stats(self) -> Dict[str, object]:
        """Dispatch counters and the current routing distribution."""
        with self._lock:
            return {
                "dispatched": self._dispatched,
                "completed": self._completed,
                "failed": self._failed,
                "in_flight": len(self._in_flight),
                "available_mirrors": list(self._monitor.available_mirrors()),
                "probabilities": self._bandit.probabilities(),
                "peak_throughput_bps": self._monitor.peak_throughput_bps,
            }

    def __repr__(self) -> str:
        return (
            f"MirrorDispatcher(mirrors={len(self._endpoints)}, "
            f"dispatched={self._dispatched}, in_flight={len(self._in_flight)})"
        )
