"""
EXP3 multi-armed bandit mirror router for ReliaDL.

Chooses which mirror to issue the next range request to when a file is
available from several CDN edges or replicas. The problem is adversarial rather
than merely noisy: an edge node's throughput depends on other tenants' load,
routing changes and cache state, none of which are stationary and none of which
are observable. EXP3 is the right tool because it assumes nothing about the
reward distribution — no independence, no stationarity, not even that rewards
are generated by a process rather than chosen to spite us.

Only the reward of the mirror actually used is observed; the counterfactual
throughput of the mirrors not chosen is unknowable. That is what makes this a
bandit rather than a prediction problem, and it is the constraint the algorithm
is built around:

    p_{m,t} = (1 - eta) * w_{m,t} / sum_j w_{j,t}  +  eta / M
    r_hat   = r / p_{m,t}
    w_{m,t+1} = w_{m,t} * exp(eta * r_hat / M)

The uniform eta/M floor does two jobs, and the second is easy to overlook.
It keeps every mirror under occasional test so a recovered edge can be
rediscovered, and it bounds every selection probability away from zero, which
is what makes the importance-weighted estimate r/p finite. Dividing by a
probability that could reach zero would be unbounded; the floor is what makes
the estimator well defined rather than merely convenient.

Dividing by the selection probability is what keeps the estimate unbiased. A
mirror chosen a tenth of the time has its observed reward scaled up tenfold, so
in expectation each arm's accumulated estimate reflects what it would have
earned had it been played every round. Without that correction the algorithm
would conflate "rarely chosen" with "low reward" and never escape its first
impression.

Numerical representation
------------------------
Weights are held as logarithms, which is a requirement rather than a
refinement. The exponent of a single update is bounded by 1 — since
r <= 1 and p >= eta/M give r_hat <= M/eta, so eta * r_hat / M <= 1 — but that
bound is per round, and it accumulates. A weight can therefore grow like e^T
over T rounds, and a long download makes tens of thousands of range requests;
e^10000 is not representable. In log space the same growth is linear and the
weights are rescaled after every update so the largest is exactly 1, which
leaves the selection distribution untouched (it depends only on weight ratios)
while keeping every exponential in range.

Tracking a moving target
------------------------
Classic EXP3 has vanishing regret against the best *fixed* arm in hindsight,
which is the wrong target here: over a long transfer the best mirror changes.
Accumulated weights make the algorithm progressively more confident and
correspondingly slower to react, so an edge that was fastest for the first ten
thousand chunks keeps its lead long after it has degraded.

The optional decay mixes each weight back toward the mean every round,

    w_m <- (1 - alpha) * w_m + (alpha / M) * sum_j w_j

which caps how much evidence any arm can hoard and gives the router a finite
memory. This is the EXP3.S variant, and it is what converts a bandit that
converges into one that tracks. With alpha = 0 the behaviour is exactly classic
EXP3.

Choosing the decay is a real tradeoff, so it was measured rather than guessed.
Regret against the best mirror in hindsight, three mirrors, eta = 0.1, averaged
over 24 seeded trials of 5000 rounds, under a stationary schedule, an abrupt
mid-transfer failover, and a gradual drift. The reward stream is seeded
independently of the router's own sampler; sharing a seed makes the two draw
identical values in lockstep and couples each reward to the arm that draw
selected, which quietly favours whichever mirror sits first in the cumulative
distribution:

    decay     stationary   switching   drifting   worst
    0                217        1709        771    1709
    0.0002           246         378        222     378
    0.0005           279         390        235     390
    0.001            333         426        256     426
    0.002            420         494        311     494
    0.004            578         633        397     633

Classic EXP3 wins the stationary column and is unusable everywhere else: having
committed to the leading mirror it cannot recover when that mirror degrades,
which is the single behaviour this router exists to avoid. Any small positive
decay cuts worst-case regret by more than four times for about a tenth more
regret in the stationary case, which is a trade worth making for a transfer
whose mirrors are not under our control.

The optimum sat at alpha = 0.0002, which is 1/T for the 5000-round horizon
measured. That is not a coincidence — it is the EXP3.S guidance alpha ~ 1/T —
and it was confirmed to hold at other horizons, alpha = 1/T minimizing
worst-case regret at T = 1000, 2000 and 10000 alike. ``decay_for_horizon``
applies that relationship for callers who know how many range requests a
transfer will make.
"""

from __future__ import annotations

import math
import random
import threading
from dataclasses import dataclass
from typing import Dict, List, Optional, Sequence, Tuple

from src.exceptions import ConfigurationError

# Fraction of each round's probability mass spread uniformly across mirrors.
# Also the floor on any selection probability, and therefore the cap on the
# importance weight 1/p.
DEFAULT_EXPLORATION_RATE = 0.1

# Per-round pull of every weight back toward the mean. Zero reproduces classic
# EXP3, which converges on the best fixed mirror; a positive value bounds the
# algorithm's memory so it can follow a mirror that degrades mid-transfer.
#
# The default corresponds to 1 / 2000 — a couple of thousand range requests,
# roughly a 16 GB transfer at the default 8 MB chunk. Callers who know their
# chunk count should pass decay_for_horizon(count) instead; see the module
# docstring for the measurements behind this.
DEFAULT_WEIGHT_DECAY = 0.0005

# Horizon the default decay is tuned for, in rounds.
DEFAULT_HORIZON_ROUNDS = 2000

# Natural log of zero, the weight of an arm that can never be selected. Used as
# the identity for log-space accumulation.
_LOG_ZERO = -math.inf


def _logaddexp(left: float, right: float) -> float:
    """
    Compute log(exp(left) + exp(right)) without leaving log space.

    Factors out the larger term so the surviving exponential has a
    non-positive argument and cannot overflow, and uses log1p for accuracy when
    the two terms are far apart and the correction is tiny.
    """
    if left == _LOG_ZERO:
        return right
    if right == _LOG_ZERO:
        return left
    higher, lower = (left, right) if left > right else (right, left)
    return higher + math.log1p(math.exp(lower - higher))


def _logsumexp(values: Sequence[float]) -> float:
    """Compute log(sum(exp(v))) by shifting out the maximum term first."""
    if not values:
        return _LOG_ZERO
    highest = max(values)
    if highest == _LOG_ZERO:
        return _LOG_ZERO
    total = sum(math.exp(value - highest) for value in values)
    return highest + math.log(total)


def decay_for_horizon(expected_rounds: int) -> float:
    """
    Weight decay for a transfer of a known length, following alpha ~ 1/T.

    The EXP3.S guidance, and measured to minimize worst-case regret at horizons
    from a thousand rounds to ten thousand. A download's horizon is the number
    of range requests it expects to issue, roughly file size over chunk size.

    Raises:
        ConfigurationError: If expected_rounds is not a positive integer.
    """
    if isinstance(expected_rounds, bool) or not isinstance(expected_rounds, int):
        raise ConfigurationError(
            f"expected_rounds must be an integer, got {type(expected_rounds).__name__}",
            parameter="expected_rounds",
            value=expected_rounds,
        )
    if expected_rounds < 1:
        raise ConfigurationError(
            f"expected_rounds must be at least 1, got {expected_rounds}",
            parameter="expected_rounds",
            value=expected_rounds,
        )
    # A one-round transfer has nothing to forget; cap at 1 so the value stays a
    # valid mixing coefficient.
    return min(1.0, 1.0 / expected_rounds)


def _validate_unit_interval(
    value: float, parameter: str, allow_zero: bool = False
) -> float:
    """
    Validate that a rate lies in (0, 1], or [0, 1] when zero is meaningful.

    Raises:
        ConfigurationError: If the value is non-numeric, non-finite, or out of range.
    """
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ConfigurationError(
            f"{parameter} must be numeric, got {type(value).__name__}",
            parameter=parameter,
            value=value,
        )
    numeric = float(value)
    if not math.isfinite(numeric):
        raise ConfigurationError(
            f"{parameter} must be finite, got {value}",
            parameter=parameter,
            value=value,
        )
    lower_ok = numeric >= 0.0 if allow_zero else numeric > 0.0
    if not lower_ok or numeric > 1.0:
        bound = "[0, 1]" if allow_zero else "(0, 1]"
        raise ConfigurationError(
            f"{parameter} must lie in {bound}, got {value}",
            parameter=parameter,
            value=value,
        )
    return numeric


@dataclass(frozen=True)
class ArmSelection:
    """
    One mirror choice, carrying the probability that produced it.

    The probability travels with the selection rather than being recomputed at
    update time, and that is a correctness requirement, not bookkeeping. The
    importance-weighted estimate r/p is only unbiased when p is the probability
    the action was actually drawn from; weights shift on every intervening
    update, so a probability recomputed later belongs to a different
    distribution and would bias every estimate in flight. A download issues
    many concurrent range requests, so rewards routinely arrive well after the
    selection that caused them.

    Attributes:
        arm: Identifier of the chosen mirror.
        probability: Probability this arm was drawn with, in (0, 1].
        round_index: Round number at which the draw was made, from zero.
    """

    arm: str
    probability: float
    round_index: int

    @property
    def importance_weight(self) -> float:
        """
        Reciprocal of the selection probability, the estimator's scale factor.

        Bounded by M / eta because the uniform exploration floor bounds the
        probability away from zero.
        """
        return 1.0 / self.probability

    def __repr__(self) -> str:
        return (
            f"ArmSelection(arm={self.arm!r}, probability={self.probability:.6f}, "
            f"round={self.round_index})"
        )


@dataclass(frozen=True)
class WeightUpdate:
    """
    Record of one weight update, retaining the intermediate terms.

    Exposed for observability and for the tests that pin the algebra: a router
    that silently mis-scales its estimates produces a plausible-looking
    distribution that quietly converges on the wrong mirror, so the terms are
    worth being able to inspect.

    Attributes:
        arm: Mirror whose weight was updated.
        reward: Observed reward in [0, 1].
        probability: Probability the arm was selected with.
        estimated_reward: Importance-weighted estimate reward / probability.
        log_weight_delta: Amount added to the arm's log weight.
        round_index: Round at which the update was applied.
    """

    arm: str
    reward: float
    probability: float
    estimated_reward: float
    log_weight_delta: float
    round_index: int

    def __repr__(self) -> str:
        return (
            f"WeightUpdate(arm={self.arm!r}, reward={self.reward:.4f}, "
            f"r_hat={self.estimated_reward:.4f}, "
            f"delta={self.log_weight_delta:.6f})"
        )


class EXP3Bandit:
    """
    Non-stationary EXP3 mirror router over a fixed set of arms.

    Thread-safe. A download engine dispatches range requests from many workers
    at once, so selection and update are serialized internally; the critical
    section is a handful of arithmetic operations over the arm set and is never
    held across I/O.

    Weights are stored as logarithms and rescaled after every update, so the
    router is safe to run for the lifetime of an arbitrarily long transfer.
    """

    def __init__(
        self,
        arms: Sequence[str],
        exploration_rate: float = DEFAULT_EXPLORATION_RATE,
        weight_decay: float = DEFAULT_WEIGHT_DECAY,
        seed: Optional[int] = None,
    ) -> None:
        validated = self._validate_arms(arms)
        self._arms: Tuple[str, ...] = validated
        self._index = {arm: position for position, arm in enumerate(validated)}
        self._eta = _validate_unit_interval(exploration_rate, "exploration_rate")
        self._decay = _validate_unit_interval(
            weight_decay, "weight_decay", allow_zero=True
        )

        # Uniform prior: every mirror starts equally plausible, since before the
        # first request there is no evidence to prefer any of them.
        self._log_weights: List[float] = [0.0] * len(validated)
        self._rounds = 0
        self._random = random.Random(seed)
        self._lock = threading.RLock()

    @staticmethod
    def _validate_arms(arms: Sequence[str]) -> Tuple[str, ...]:
        """
        Validate the mirror set.

        Duplicates are rejected rather than collapsed: two entries for one
        mirror would split its evidence across two weights and let it draw
        twice the exploration mass, quietly biasing the router toward whichever
        mirror happened to be listed twice.
        """
        materialized = tuple(arms)
        if not materialized:
            raise ConfigurationError(
                "At least one mirror is required to route between",
                parameter="arms",
                value=arms,
            )
        seen = set()
        for arm in materialized:
            if not isinstance(arm, str) or not arm:
                raise ConfigurationError(
                    f"Mirror identifiers must be non-empty strings, got {arm!r}",
                    parameter="arms",
                    value=arm,
                )
            if arm in seen:
                raise ConfigurationError(
                    f"Duplicate mirror identifier {arm!r}",
                    parameter="arms",
                    value=arm,
                )
            seen.add(arm)
        return materialized

    @property
    def arms(self) -> Tuple[str, ...]:
        """Mirrors being routed between, in their configured order."""
        return self._arms

    @property
    def arm_count(self) -> int:
        """Number of mirrors, the M of the formulation."""
        return len(self._arms)

    @property
    def exploration_rate(self) -> float:
        """Uniform probability mass reserved for exploration, the eta."""
        return self._eta

    @property
    def weight_decay(self) -> float:
        """Per-round pull toward the mean; zero is classic EXP3."""
        return self._decay

    @property
    def rounds(self) -> int:
        """Number of updates absorbed so far."""
        return self._rounds

    @property
    def min_probability(self) -> float:
        """
        Floor on any arm's selection probability.

        The reciprocal caps the importance weight, which is what keeps the
        reward estimator bounded.
        """
        return self._eta / self.arm_count

    @property
    def max_log_weight_delta(self) -> float:
        """
        Largest log-weight increment a single round can produce.

        Equals 1.0 for any configuration: r <= 1 and p >= eta/M bound r_hat by
        M/eta, so eta * r_hat / M <= 1 regardless of how eta and M are chosen.
        """
        return self._eta * (1.0 / self.min_probability) / self.arm_count

    def _distribution_locked(self) -> List[float]:
        """
        Mix the weight-proportional distribution with the uniform floor.

        Computed as a softmax over log weights, so no weight is ever
        exponentiated into a range where it could overflow.
        """
        total = _logsumexp(self._log_weights)
        uniform = self._eta / self.arm_count
        if total == _LOG_ZERO:
            # Every weight has decayed to zero; fall back to uniform rather
            # than dividing by nothing.
            return [1.0 / self.arm_count] * self.arm_count
        return [
            (1.0 - self._eta) * math.exp(log_weight - total) + uniform
            for log_weight in self._log_weights
        ]

    def probabilities(self) -> Dict[str, float]:
        """Current selection distribution over mirrors, summing to 1."""
        with self._lock:
            return dict(zip(self._arms, self._distribution_locked()))

    def probability(self, arm: str) -> float:
        """Current selection probability of one mirror."""
        with self._lock:
            return self._distribution_locked()[self._require_arm(arm)]

    def weights(self) -> Dict[str, float]:
        """
        Weights normalized to sum to 1, for observability.

        The raw log weights are an implementation detail whose absolute scale is
        arbitrary after rescaling; the normalized form is what carries meaning.
        """
        with self._lock:
            total = _logsumexp(self._log_weights)
            if total == _LOG_ZERO:
                return {arm: 0.0 for arm in self._arms}
            return {
                arm: math.exp(log_weight - total)
                for arm, log_weight in zip(self._arms, self._log_weights)
            }

    def log_weights(self) -> Dict[str, float]:
        """Raw log weights, exposed for state persistence and diagnostics."""
        with self._lock:
            return dict(zip(self._arms, self._log_weights))

    def _require_arm(self, arm: str) -> int:
        """Resolve a mirror identifier to its position, or raise."""
        position = self._index.get(arm)
        if position is None:
            raise ConfigurationError(
                f"Unknown mirror {arm!r}; known mirrors are {list(self._arms)}",
                parameter="arm",
                value=arm,
            )
        return position

    def select(self) -> ArmSelection:
        """
        Draw a mirror from the current distribution.

        Returns the probability alongside the arm so the reward can be scaled by
        the distribution that actually produced the draw, however long it takes
        to arrive.
        """
        with self._lock:
            distribution = self._distribution_locked()
            target = self._random.random()
            cumulative = 0.0
            chosen = self.arm_count - 1
            for position, probability in enumerate(distribution):
                cumulative += probability
                if target < cumulative:
                    chosen = position
                    break
            # Falling through to the last arm covers the case where accumulated
            # floating-point error leaves the total a hair below 1.0.
            return ArmSelection(
                arm=self._arms[chosen],
                probability=distribution[chosen],
                round_index=self._rounds,
            )

    def update(self, selection: ArmSelection, reward: float) -> WeightUpdate:
        """
        Absorb the reward observed for a previously selected mirror.

        Raises:
            ConfigurationError: If the arm is unknown or the reward is outside [0, 1].
        """
        return self.update_arm(selection.arm, reward, selection.probability)

    def update_arm(self, arm: str, reward: float, probability: float) -> WeightUpdate:
        """
        Absorb a reward given the arm and the probability it was drawn with.

        The primitive form, for callers that persist the selection across a
        process boundary rather than holding the ArmSelection object.

        Raises:
            ConfigurationError: If the arm is unknown, the reward lies outside
                [0, 1], or the probability is not a valid selection probability.
        """
        position = self._require_arm(arm)
        normalized_reward = self._validate_reward(reward)

        if isinstance(probability, bool) or not isinstance(probability, (int, float)):
            raise ConfigurationError(
                f"probability must be numeric, got {type(probability).__name__}",
                parameter="probability",
                value=probability,
            )
        numeric_probability = float(probability)
        if not math.isfinite(numeric_probability) or not (
            0.0 < numeric_probability <= 1.0
        ):
            raise ConfigurationError(
                f"probability must lie in (0, 1], got {probability}",
                parameter="probability",
                value=probability,
            )

        with self._lock:
            estimated = normalized_reward / numeric_probability
            delta = self._eta * estimated / self.arm_count
            self._log_weights[position] += delta

            if self._decay > 0.0:
                self._apply_decay_locked()

            self._rescale_locked()
            self._rounds += 1

            return WeightUpdate(
                arm=arm,
                reward=normalized_reward,
                probability=numeric_probability,
                estimated_reward=estimated,
                log_weight_delta=delta,
                round_index=self._rounds - 1,
            )

    @staticmethod
    def _validate_reward(reward: float) -> float:
        """
        Validate that a reward is a finite number in [0, 1].

        The bound is not cosmetic: the guarantee that a single update cannot
        move a log weight by more than 1 rests on r <= 1, and an unnormalized
        throughput in bytes per second would move it by billions and erase every
        other mirror in one round.
        """
        if isinstance(reward, bool) or not isinstance(reward, (int, float)):
            raise ConfigurationError(
                f"reward must be numeric, got {type(reward).__name__}",
                parameter="reward",
                value=reward,
            )
        numeric = float(reward)
        if not math.isfinite(numeric) or not 0.0 <= numeric <= 1.0:
            raise ConfigurationError(
                f"reward must be a finite value in [0, 1], got {reward}",
                parameter="reward",
                value=reward,
            )
        return numeric

    def _apply_decay_locked(self) -> None:
        """
        Mix every weight toward the mean, bounding the router's memory.

        The EXP3.S step, carried out entirely in log space:

            w_m <- (1 - alpha) * w_m + (alpha / M) * sum_j w_j
        """
        total = _logsumexp(self._log_weights)
        if total == _LOG_ZERO:
            return
        keep = math.log1p(-self._decay) if self._decay < 1.0 else _LOG_ZERO
        share = math.log(self._decay / self.arm_count) + total
        self._log_weights = [
            _logaddexp(keep + log_weight, share) for log_weight in self._log_weights
        ]

    def _rescale_locked(self) -> None:
        """
        Shift the log weights so the largest is exactly zero.

        The selection distribution depends only on ratios between weights, so a
        common shift leaves it exactly unchanged.

        This is hygiene rather than a correctness requirement, and worth being
        precise about. Every exponential in this module is taken of a
        *difference* — against the log-sum in the distribution, against the
        larger term in _logaddexp — so the distribution stays valid even with
        the raw weights left to drift; disabling this and running 200000
        rounds leaves a log weight at 200000 and the probabilities still exact.
        What it buys is bounded stored magnitudes: serialized state stays small
        and readable, absolute precision does not erode as the exponent grows,
        and no future code path can exponentiate a raw weight by accident.
        """
        highest = max(self._log_weights)
        if highest == _LOG_ZERO or highest == 0.0:
            return
        self._log_weights = [
            log_weight - highest for log_weight in self._log_weights
        ]

    def reset(self) -> None:
        """Return every mirror to the uniform prior."""
        with self._lock:
            self._log_weights = [0.0] * self.arm_count
            self._rounds = 0

    def best_arm(self) -> str:
        """
        Mirror currently carrying the most weight.

        Reports the router's belief; it is not what ``select`` returns, which
        samples so that weaker mirrors keep being tested.
        """
        with self._lock:
            best = max(range(self.arm_count), key=lambda i: self._log_weights[i])
            return self._arms[best]

    def to_dict(self) -> Dict[str, object]:
        """
        Serialize the router for crash-resilient resume.

        Log weights are persisted directly. Their absolute scale is arbitrary
        after rescaling but the differences between them are the learned state,
        so they must be stored together and restored as a set.
        """
        with self._lock:
            return {
                "arms": list(self._arms),
                "log_weights": list(self._log_weights),
                "exploration_rate": self._eta,
                "weight_decay": self._decay,
                "rounds": self._rounds,
            }

    @classmethod
    def from_dict(
        cls, data: Dict[str, object], seed: Optional[int] = None
    ) -> "EXP3Bandit":
        """
        Restore a router from its serialized form.

        Raises:
            ConfigurationError: If a required key is missing or the stored
                weight vector does not match the stored mirror set.
        """
        for key in ("arms", "log_weights", "exploration_rate", "weight_decay"):
            if key not in data:
                raise ConfigurationError(
                    f"Serialized bandit is missing required key '{key}'",
                    parameter=key,
                    value=data,
                )
        arms = data["arms"]
        log_weights = data["log_weights"]
        if not isinstance(arms, (list, tuple)) or not isinstance(
            log_weights, (list, tuple)
        ):
            raise ConfigurationError(
                "Serialized 'arms' and 'log_weights' must both be sequences",
                parameter="arms",
                value=data,
            )
        if len(arms) != len(log_weights):
            raise ConfigurationError(
                f"Serialized bandit has {len(arms)} mirrors but "
                f"{len(log_weights)} weights",
                parameter="log_weights",
                value=data,
            )

        bandit = cls(
            arms=list(arms),
            exploration_rate=float(data["exploration_rate"]),  # type: ignore[arg-type]
            weight_decay=float(data["weight_decay"]),  # type: ignore[arg-type]
            seed=seed,
        )
        restored: List[float] = []
        for weight in log_weights:
            if isinstance(weight, bool) or not isinstance(weight, (int, float)):
                raise ConfigurationError(
                    f"Serialized log weight must be numeric, got {weight!r}",
                    parameter="log_weights",
                    value=weight,
                )
            numeric = float(weight)
            if math.isnan(numeric) or numeric == math.inf:
                raise ConfigurationError(
                    f"Serialized log weight must be finite or -inf, got {weight!r}",
                    parameter="log_weights",
                    value=weight,
                )
            restored.append(numeric)

        with bandit._lock:
            bandit._log_weights = restored
            bandit._rescale_locked()
            bandit._rounds = int(data.get("rounds", 0))  # type: ignore[call-overload]
        return bandit

    def __repr__(self) -> str:
        return (
            f"EXP3Bandit(arms={len(self._arms)}, eta={self._eta}, "
            f"decay={self._decay}, rounds={self._rounds})"
        )
