"""
ReliaDL Core Package.
Fault-tolerant, high-throughput chunked download engine.
"""

from __future__ import annotations

from reliadl.config import (
    apply_env_overrides,
    deep_merge,
    format_size,
    get_download_config,
    load_config,
    load_yaml_file,
    parse_size,
)
from reliadl.rate_limiter import (
    DEFAULT_BURST_SECONDS,
    BucketState,
    TokenBucketRateLimiter,
    UnlimitedRateLimiter,
)
from reliadl.telemetry.metrics import (
    Counter,
    DownloadMetrics,
    Gauge,
    Histogram,
    MetricsRegistry,
    MetricsServer,
)
from reliadl.algorithms.adaptive_chunker import (
    BLDCSController,
    ChunkSizingDecision,
    DynamicChunkPlanner,
    align_to_power_of_two,
    is_power_of_two,
)
from reliadl.algorithms.metrics_collector import (
    DEFAULT_DEVIATION_ALPHA,
    DEFAULT_FAILURE_WINDOW_SIZE,
    DEFAULT_RTT_ALPHA,
    DEFAULT_THROUGHPUT_BETA,
    EWMAEstimator,
    FailureWindow,
    NetworkMetricsCollector,
    NetworkStateSnapshot,
    TransferSample,
)
from reliadl.exceptions import (
    AllocationError,
    AssemblyError,
    AssemblyFailedError,
    ChunkGuardError,
    ChunkHashMismatchError,
    ClientError,
    ConfigurationError,
    ConnectionError,
    DiskFullError,
    DownloadCancelledError,
    FileHashMismatchError,
    HTTPError,
    IntegrityError,
    ManifestError,
    ManifestFormatError,
    ManifestSignatureMismatchError,
    NetworkError,
    PermissionError,
    PreconditionFailedError,
    ProxyAuthenticationError,
    ProxyConnectionError,
    ProxyError,
    RangeNotSupportedError,
    ReliaDLError,
    ServerError,
    StateCorruptedError,
    StateError,
    StateNotFoundError,
    StorageError,
    StoragePermissionError,
    SubBlockCorruptedError,
    TimeoutError,
)
from reliadl.download_engine import (
    DownloadEngine,
    RemoteFileInfo,
    plan_chunks,
)
from reliadl.file_assembler import (
    DEFAULT_ASSEMBLY_BUFFER_SIZE,
    FileAssembler,
)
from reliadl.hash_verifier import (
    DEFAULT_BUFFER_SIZE,
    StreamingHashVerifier,
    async_verify_file_hash,
    compute_file_hash,
    constant_time_compare,
    normalize_hash,
    verify_file_hash,
    verify_stream,
)
from reliadl.logger import (
    configure_logger,
    get_logger,
    redact_credentials,
)
from reliadl.models import (
    ChunkResult,
    ChunkSpec,
    ChunkState,
    ChunkStatus,
    DownloadConfig,
    DownloadResult,
    DownloadState,
    DownloadStatistics,
    DownloadStatus,
    ProgressReport,
)
from reliadl.sparse_writer import (
    AllocationStrategy,
    SparseFileWriter,
)
from reliadl.state_manager import (
    CHUNK_FILE_PERMISSIONS,
    STATE_FILE_PERMISSIONS,
    StateManager,
)
from reliadl.manifest import (
    DEFAULT_SUB_BLOCK_SIZE,
    ArtifactMetadata,
    BinaryMerkleTree,
    ChunkingTopology,
    ChunkManifest,
    ManifestChunk,
    ManifestGenerator,
    MANIFEST_JSON_SCHEMA,
    ManifestSignature,
    MirrorSpec,
    SubBlockStreamValidator,
    calculate_sub_blocks,
    canonicalize_json,
    compute_merkle_root,
    dump_manifest,
    generate_ed25519_keypair,
    generate_rsa_keypair,
    hash_leaf,
    hash_parent,
    load_manifest,
    parse_manifest_json,
    sign_manifest,
    validate_manifest_dict,
    verify_manifest_signature,
)

__all__ = [
    # Enums & Models
    "ChunkStatus",
    "DownloadStatus",
    "ChunkSpec",
    "ChunkResult",
    "ChunkState",
    "DownloadStatistics",
    "DownloadState",
    "DownloadResult",
    "VerificationResult",
    "ProgressReport",
    "DownloadConfig",
    # Exceptions
    "ReliaDLError",
    "ChunkGuardError",
    "ConfigurationError",
    "NetworkError",
    "ConnectionError",
    "TimeoutError",
    "HTTPError",
    "ClientError",
    "ServerError",
    "PreconditionFailedError",
    "ProxyError",
    "ProxyConnectionError",
    "ProxyAuthenticationError",
    "ManifestError",
    "ManifestSignatureMismatchError",
    "ManifestFormatError",
    "IntegrityError",
    "ChunkHashMismatchError",
    "SubBlockCorruptedError",
    "FileHashMismatchError",
    "StorageError",
    "DiskFullError",
    "PermissionError",
    "StoragePermissionError",
    "AllocationError",
    "StateError",
    "StateNotFoundError",
    "StateCorruptedError",
    "AssemblyError",
    "AssemblyFailedError",
    "RangeNotSupportedError",
    "DownloadCancelledError",
    # Download Engine
    "DownloadEngine",
    "RemoteFileInfo",
    "plan_chunks",
    # Config
    "parse_size",
    "format_size",
    "load_yaml_file",
    "deep_merge",
    "apply_env_overrides",
    "load_config",
    "get_download_config",
    # Hash Verifier
    "DEFAULT_BUFFER_SIZE",
    "StreamingHashVerifier",
    "normalize_hash",
    "constant_time_compare",
    "compute_file_hash",
    "verify_file_hash",
    "verify_stream",
    "async_verify_file_hash",
    # Logger
    "configure_logger",
    "get_logger",
    "redact_credentials",
    # State Manager
    "StateManager",
    "STATE_FILE_PERMISSIONS",
    "CHUNK_FILE_PERMISSIONS",
    # File Assembler
    "FileAssembler",
    "DEFAULT_ASSEMBLY_BUFFER_SIZE",
    # Sparse Writer
    "SparseFileWriter",
    "AllocationStrategy",
    # Manifest
    "MANIFEST_JSON_SCHEMA",
    "ManifestGenerator",
    "ArtifactMetadata",
    "MirrorSpec",
    "ChunkingTopology",
    "ManifestChunk",
    "ManifestSignature",
    "ChunkManifest",
    "validate_manifest_dict",
    "parse_manifest_json",
    "load_manifest",
    "dump_manifest",
    "canonicalize_json",
    "generate_ed25519_keypair",
    "generate_rsa_keypair",
    "sign_manifest",
    "verify_manifest_signature",
    "DEFAULT_SUB_BLOCK_SIZE",
    "BinaryMerkleTree",
    "SubBlockStreamValidator",
    "calculate_sub_blocks",
    "compute_merkle_root",
    "hash_leaf",
    "hash_parent",
    # Algorithms
    "DEFAULT_RTT_ALPHA",
    "DEFAULT_THROUGHPUT_BETA",
    "DEFAULT_DEVIATION_ALPHA",
    "DEFAULT_FAILURE_WINDOW_SIZE",
    "EWMAEstimator",
    "FailureWindow",
    "TransferSample",
    "NetworkStateSnapshot",
    "NetworkMetricsCollector",
    "BLDCSController",
    "ChunkSizingDecision",
    "DynamicChunkPlanner",
    "align_to_power_of_two",
    "is_power_of_two",
    # Bandwidth rate limiting
    "DEFAULT_BURST_SECONDS",
    "BucketState",
    "TokenBucketRateLimiter",
    "UnlimitedRateLimiter",
    # Telemetry
    "Counter",
    "Gauge",
    "Histogram",
    "MetricsRegistry",
    "MetricsServer",
    "DownloadMetrics",
]
