"""
ReliaDL Core Package.
Fault-tolerant, high-throughput chunked download engine.
"""

from __future__ import annotations

from src.config import (
    apply_env_overrides,
    deep_merge,
    format_size,
    get_download_config,
    load_config,
    load_yaml_file,
    parse_size,
)
from src.exceptions import (
    AllocationError,
    AssemblyError,
    AssemblyFailedError,
    ChunkGuardError,
    ChunkHashMismatchError,
    ClientError,
    ConfigurationError,
    ConnectionError,
    DiskFullError,
    FileHashMismatchError,
    HTTPError,
    IntegrityError,
    ManifestError,
    ManifestFormatError,
    ManifestSignatureMismatchError,
    NetworkError,
    PermissionError,
    PreconditionFailedError,
    ProxyAuthenticationError,
    ProxyConnectionError,
    ProxyError,
    ReliaDLError,
    ServerError,
    StateCorruptedError,
    StateError,
    StateNotFoundError,
    StorageError,
    StoragePermissionError,
    TimeoutError,
)
from src.file_assembler import (
    DEFAULT_ASSEMBLY_BUFFER_SIZE,
    FileAssembler,
)
from src.hash_verifier import (
    DEFAULT_BUFFER_SIZE,
    StreamingHashVerifier,
    async_verify_file_hash,
    compute_file_hash,
    constant_time_compare,
    normalize_hash,
    verify_file_hash,
    verify_stream,
)
from src.logger import (
    configure_logger,
    get_logger,
    redact_credentials,
)
from src.models import (
    ChunkResult,
    ChunkSpec,
    ChunkState,
    ChunkStatus,
    DownloadConfig,
    DownloadResult,
    DownloadState,
    DownloadStatistics,
    DownloadStatus,
    ProgressReport,
)
from src.sparse_writer import (
    AllocationStrategy,
    SparseFileWriter,
)
from src.state_manager import (
    CHUNK_FILE_PERMISSIONS,
    STATE_FILE_PERMISSIONS,
    StateManager,
)
from src.manifest import (
    MANIFEST_JSON_SCHEMA,
    ArtifactMetadata,
    ChunkingTopology,
    ChunkManifest,
    ManifestChunk,
    ManifestGenerator,
    ManifestSignature,
    MirrorSpec,
    dump_manifest,
    load_manifest,
    parse_manifest_json,
    validate_manifest_dict,
)
from src.manifest import (
    MANIFEST_JSON_SCHEMA,
    ArtifactMetadata,
    ChunkingTopology,
    ChunkManifest,
    ManifestChunk,
    ManifestGenerator,
    ManifestSignature,
    MirrorSpec,
    dump_manifest,
    load_manifest,
    parse_manifest_json,
    validate_manifest_dict,
    canonicalize_json,
    generate_ed25519_keypair,
    generate_rsa_keypair,
    sign_manifest,
    verify_manifest_signature,
)

__all__ = [
    # Enums & Models
    "ChunkStatus",
    "DownloadStatus",
    "ChunkSpec",
    "ChunkResult",
    "ChunkState",
    "DownloadStatistics",
    "DownloadState",
    "DownloadResult",
    "VerificationResult",
    "ProgressReport",
    "DownloadConfig",
    # Exceptions
    "ReliaDLError",
    "ChunkGuardError",
    "ConfigurationError",
    "NetworkError",
    "ConnectionError",
    "TimeoutError",
    "HTTPError",
    "ClientError",
    "ServerError",
    "PreconditionFailedError",
    "ProxyError",
    "ProxyConnectionError",
    "ProxyAuthenticationError",
    "ManifestError",
    "ManifestSignatureMismatchError",
    "ManifestFormatError",
    "IntegrityError",
    "ChunkHashMismatchError",
    "FileHashMismatchError",
    "StorageError",
    "DiskFullError",
    "PermissionError",
    "StoragePermissionError",
    "AllocationError",
    "StateError",
    "StateNotFoundError",
    "StateCorruptedError",
    "AssemblyError",
    "AssemblyFailedError",
    # Config
    "parse_size",
    "format_size",
    "load_yaml_file",
    "deep_merge",
    "apply_env_overrides",
    "load_config",
    "get_download_config",
    # Hash Verifier
    "DEFAULT_BUFFER_SIZE",
    "StreamingHashVerifier",
    "normalize_hash",
    "constant_time_compare",
    "compute_file_hash",
    "verify_file_hash",
    "verify_stream",
    "async_verify_file_hash",
    # Logger
    "configure_logger",
    "get_logger",
    "redact_credentials",
    # State Manager
    "StateManager",
    "STATE_FILE_PERMISSIONS",
    "CHUNK_FILE_PERMISSIONS",
    # File Assembler
    "FileAssembler",
    "DEFAULT_ASSEMBLY_BUFFER_SIZE",
    # Sparse Writer
    "SparseFileWriter",
    "AllocationStrategy",
    # Manifest
    "MANIFEST_JSON_SCHEMA",
    "ManifestGenerator",
    "ArtifactMetadata",
    "MirrorSpec",
    "ChunkingTopology",
    "ManifestChunk",
    "ManifestSignature",
    "ChunkManifest",
    "validate_manifest_dict",
    "parse_manifest_json",
    "load_manifest",
    "dump_manifest",
    "canonicalize_json",
    "generate_ed25519_keypair",
    "generate_rsa_keypair",
    "sign_manifest",
    "verify_manifest_signature",
]
