"""
ReliaDL Core Package.
Fault-tolerant, high-throughput chunked download engine.
"""

from __future__ import annotations

from src.config import (
    apply_env_overrides,
    deep_merge,
    format_size,
    get_download_config,
    load_config,
    load_yaml_file,
    parse_size,
)
from src.exceptions import (
    AllocationError,
    AssemblyError,
    AssemblyFailedError,
    ChunkGuardError,
    ChunkHashMismatchError,
    ClientError,
    ConfigurationError,
    ConnectionError,
    DiskFullError,
    FileHashMismatchError,
    HTTPError,
    IntegrityError,
    ManifestError,
    ManifestFormatError,
    ManifestSignatureMismatchError,
    NetworkError,
    PermissionError,
    PreconditionFailedError,
    ProxyAuthenticationError,
    ProxyConnectionError,
    ProxyError,
    ReliaDLError,
    ServerError,
    StateCorruptedError,
    StateError,
    StateNotFoundError,
    StorageError,
    StoragePermissionError,
    TimeoutError,
)
from src.logger import (
    configure_logger,
    get_logger,
    redact_credentials,
)
from src.models import (
    ChunkResult,
    ChunkSpec,
    ChunkState,
    ChunkStatus,
    DownloadConfig,
    DownloadResult,
    DownloadState,
    DownloadStatistics,
    DownloadStatus,
    ProgressReport,
    VerificationResult,
)

__all__ = [
    # Enums & Models
    "ChunkStatus",
    "DownloadStatus",
    "ChunkSpec",
    "ChunkResult",
    "ChunkState",
    "DownloadStatistics",
    "DownloadState",
    "DownloadResult",
    "VerificationResult",
    "ProgressReport",
    "DownloadConfig",
    # Exceptions
    "ReliaDLError",
    "ChunkGuardError",
    "ConfigurationError",
    "NetworkError",
    "ConnectionError",
    "TimeoutError",
    "HTTPError",
    "ClientError",
    "ServerError",
    "PreconditionFailedError",
    "ProxyError",
    "ProxyConnectionError",
    "ProxyAuthenticationError",
    "ManifestError",
    "ManifestSignatureMismatchError",
    "ManifestFormatError",
    "IntegrityError",
    "ChunkHashMismatchError",
    "FileHashMismatchError",
    "StorageError",
    "DiskFullError",
    "PermissionError",
    "StoragePermissionError",
    "AllocationError",
    "StateError",
    "StateNotFoundError",
    "StateCorruptedError",
    "AssemblyError",
    "AssemblyFailedError",
    # Config
    "parse_size",
    "format_size",
    "load_yaml_file",
    "deep_merge",
    "apply_env_overrides",
    "load_config",
    "get_download_config",
    # Logger
    "configure_logger",
    "get_logger",
    "redact_credentials",
]
